### PR TITLE
Meteor 1.2.1

### PR DESCRIPTION
**Pull request by pradel**
A new bundle for Meteor 1.2.1
I created a `src/packages` file containing all dependencies for meteor-base but without hot-code-push (containing autoupdate and reload packages).

### CODE REVIEW

**Comment by idanwe** [comment]
Thank you very much!
I'm very glad for upgrading to meteor 1.2.

I think that the autoupdate and the reload package should be in a different bundle or package.
It is an addition layer of meteor in my opinion,
and it is good that will be an option to use meteor-client-side w/o it.

Can you split it to different bundle those too packages?

**Comment by pradel** [comment]
I removed livedata and webapp. For hot-code-push see https://forums.meteor.com/t/remove-hot-code-push-from-meteor-packages/16213/5 Maybe they will remove it from meteor-base ?

Creating different repos like meteor-webapp-client-side, meteor-hot-code-push-client-side etc .. will be hard to maintain I think maybe it's better to use the same method as meteor repository https://github.com/meteor/meteor/tree/devel/packages and like that you will be able to take only what you need in dist folder, meteor-base.bundle.min.js, hot-code-push.bundle.min.js, account-base.bundle.min.js etc .. what do you think about that?

**Comment by pradel** [comment]
Added separate bundles for webapp and hot-code-push.

**Comment by idanwe** [comment]
Great work!
Really like the separation you made.

thanks!

Closes #2

**Pull request merged**
